### ISSUE TITLE
Problem in finding styles

### ISSUE THREAD

**Issue by eykaraduman** [PieroCastillo/Aura.UI#35]
Hi,
I create a new avalonia project with jetbrains rider and add the styles below to App.xaml. (target framework is net 6.0)
`<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:Avalonia.NETCoreMVVMApp1"
             x:Class="Avalonia.NETCoreMVVMApp1.App">
    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>

    
    
    
    <Application.Styles>
        <StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseLight.xaml"/>
        <StyleInclude Source="avares://Aura.UI.FluentTheme/AuraUI.xaml"/>
        <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml"/>
        <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
    </Application.Styles> 
</Application>`

I get an exception in row <StyleInclude Source="avares://Aura.UI.FluentTheme/AuraUI.xaml"/>.

How can i solve this problem?

**Comment by PieroCastillo** [comment]
What's the exception?

**Comment by eykaraduman** [comment]
> What's the exception?

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.UInt64.Parse(String s, IFormatProvider provider)
   at Avalonia.Animation.IterationCount.Parse(String s) in /_/src/Avalonia.Animation/IterationCount.cs:line 167
   at Avalonia.Animation.Animation.set_RepeatCount(String value) in /_/src/Avalonia.Animation/Animation.cs:line 188
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Controls/ProgressRing.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Controls/ProgressRing.xaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Markup.Xaml.MarkupExtensions.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs:line 48
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Controls/RibbonStyles.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Controls/RibbonStyles.xaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Markup.Xaml.MarkupExtensions.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs:line 48
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Controls/RadialSlider.xaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Controls/RadialSlider.xaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 89
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryGetResource(Object key, Object& value) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 91
   at Avalonia.Styling.Styles.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 163
   at Avalonia.Application.Avalonia.Controls.IResourceNode.TryGetResource(Object key, Object& value) in /_/src/Avalonia.Controls/Application.cs:line 201
   at Avalonia.Controls.ResourceNodeExtensions.TryFindResource(IResourceHost control, Object key, Object& value) in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 49
   at Avalonia.Controls.ResourceNodeExtensions.FindResource(IResourceHost control, Object key) in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 23
   at Avalonia.Controls.ResourceNodeExtensions.FloatingResourceObservable.PublishNext() in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 158
   at Avalonia.Controls.ResourceNodeExtensions.FloatingResourceObservable.ResourcesChanged(Object sender, ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs:line 181
   at Avalonia.Application.Avalonia.Controls.IResourceHost.NotifyHostedResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Controls/Application.cs:line 208
   at Avalonia.Controls.ResourceDictionary.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Controls/ResourceDictionary.cs:line 150
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 234
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 240
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 240
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 289
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 681
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at Avalonia.NETCoreMVVMApp1.App.!XamlIlPopulate(IServiceProvider , App ) in D:\NetProgramming\Uygulamalar\Avalonia.NETCoreMVVMApp1\App.axaml:line 15
   at Avalonia.NETCoreMVVMApp1.App.!XamlIlPopulateTrampoline(App ) in D:\NetProgramming\Uygulamalar\Avalonia.NETCoreMVVMApp1\App.axaml:line 0
   at Avalonia.NETCoreMVVMApp1.App.Initialize() in D:\NetProgramming\Uygulamalar\Avalonia.NETCoreMVVMApp1\App.axaml.cs:line 13
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Avalonia.NETCoreMVVMApp1.Program.Main(String[] args) in D:\NetProgramming\Uygulamalar\Avalonia.NETCoreMVVMApp1\Program.cs:line 14

**Comment by braca** [comment]
Any update on this?
I've got the same issue, but for some reason it only happens on some systems 🤔
